name: Sync to Upstream
run-name: Sync fork

on:
  schedule:
    - cron: "12 7 * * 1,4"
  # scheduled at 07:12 every Monday and Thursday
  workflow-dispatch

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout HEAD
        uses: actions/checkout@v3
        with:
          ref: main
          node-version: "14"

      # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
      - name: Pull upstream changes
        id: sync
        uses: bdougie/Fork-Sync-With-Upstream-action@fork
        with:
          upstream_repository: itdevsamurai/atlassian-plugin-remote-install
          upstream_branch: main
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }} # optional, for accessing repos that require authentication
