name: Sync fork
run-name: ${{ github.actor }} sync his own fork
on: [push]

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fork Sync
        uses: tgymnich/fork-sync@v1.2.1
        with:
          owner: merhuman
          base: personal
          head: master
